### ISSUE TITLE
BUG: picking tiles, scrollbar do whatever it wants

### ISSUE THREAD

**Issue by jmwielandt** [huderlem/porymap#100]
Single click to pick a tile and scrollbar goes up or down, selecting multiple tiles.

![image](https://user-images.githubusercontent.com/37153467/53291564-f6b09a80-3793-11e9-86b1-5cc5b85f1ffe.png)

**Comment by Gamer2020** [comment]
I can confirm this. Haven't had a chance to report it, seems to be something with the zoom feature.

Get Outlook for Android

________________________________

**Comment by garakmon** [comment]
okay I've identified the issue

**Comment by tustin2121** [comment]
Any plans on including this in a bugfix release soon? (Especially for those of us who use porymap on Windows, seeing as there's no instructions on how to build on Windows...?)

**Comment by huderlem** [comment]
@tustin2121 likely this weekend
