### ISSUE TITLE
Compatibility with Linux

### ISSUE THREAD

**Issue by Dafting** [huderlem/porymap#102]
I use pokeemerald in Linux, and since some version i don't really know (probably 1.2.0) the Windows version (running in Wine) cannot read the folder of the project properly. I tried selecting "pokeemerald", "data", "maps", but none works.

It is possible to do a version in Linux?

PS: I love this tool, keep the good work!

**Comment by huderlem** [comment]
All of the releases can be download in the Releases tab.   Could you please confirm which version introduced this issue?

**Comment by mid-kid** [comment]
You can build porymap for linux yourself, as described in INSTALL.md for ubuntu/debian and derivatives.

**Comment by Dafting** [comment]
It seems that 1.0.6 and 1.1.0 works flawlessly, but 1.2.0 and 1.2.1 not.

**Comment by Dafting** [comment]
> You can build porymap for linux yourself, as described in INSTALL.md for ubuntu/debian and derivatives.

I'm a bit new on this thing of 'compiling' stuff for Linux. I would totally do it, but i don't really understands how it works.

**Comment by mid-kid** [comment]
There's very little to understand except copying those commands into your terminal.
Use:
```
sudo apt-get install git qt5-default
git clone https://github.com/huderlem/porymap
cd porymap
git checkout 1.2.1
qmake
make
./porymap
```
Once done, you should have a folder in your home folder called "porymap" with the executable inside.

**Comment by Dafting** [comment]
Ok, i guess everything compiled fine, but STILL the folder does not open when i select "pokeemerald" from my user folder (home/j****in).

Probably it's an error with the version itself and not from compatibility with Wine?

**Comment by SBird1337** [comment]
See the breaking changes: https://github.com/huderlem/porymap/blob/master/CHANGELOG.md

Version 1.2.0 introduced a new map format, which forces you to be on a poke* version that also introduced that change, the exact commit hashes can be found in the release info. You can also use the latest version of poke* airc.

**Comment by huderlem** [comment]
Ah, that is almost certainly the issue you're facing.  Unfortunately porymap is very prone to crashing if it is trying to process unexpected data.  Until the crashing issue is addressed, users need to be mindful of what version they are using.  I try to document very clearly when there are breaking changes, as seen in the changelog.
