### ISSUE TITLE
Display event object sprites in the "facing direction" according to their movement type

### ISSUE THREAD

**Issue by huderlem** [huderlem/porymap#103]
For example, if the movement type is "FACING_RIGHT", it would be nice to see the sprite displayed as facing right, rather than its default frame, which is facing down.

**Comment by garakmon** [comment]
In the object frame, do you think the sprite should use the facing direction or the default?
![image](https://user-images.githubusercontent.com/13525717/55438688-573fae00-5570-11e9-84ed-884b1f1722d1.png)

**Comment by huderlem** [comment]
I could see either way, but I think making them both match is the least surprising to the user.
