### ISSUE TITLE
Ask the user to provide a default editor

### ISSUE THREAD

**Issue by SBird1337** [huderlem/porymap#120]
Currently when clicking on "Open Map Scripts" porymap will use the operating system's default editor, e.g. as determined by the mime-type on linux. There is 2 issues with that:

First: If there is not default editor set, this does absolutely nothing
Second: Porymap should ask the user to provide an editor, and probably allow for a command skeleton with printf-like replacements, e.g. `code -g %f:%l` would open script files with visual studio code at line %l (which is most likely 0 if we dont know the position of a script symbol e.g.)

**Comment by BigBahss** [comment]
This issue can be closed with #325 merged.
