### ISSUE TITLE
Renaming Map Group Names Messes Up Dropdown For Creating New Maps

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#140]
If you go into your map_groups.json and rename your map groups, you will not be able to select the appropriate group when creating a new map in porymap. It seems to select the appropriate map group by default when you right click a group to add a map, but the group will be using the old naming scheme (i.e., gMapGroup13 instead of your renamed one. Leaving it like this will put your map in the group you initially right-clicked on as long as you don't go into the dropdown menu). The group dropdown box uses the renamed groups, but selecting one will instead add your map to the first map group. Adding a map with an existing layout will always add to the first map group, because selecting renamed groups from the dropdown will always do that.

**Comment by SBird1337** [comment]
dup of #132 ?

**Comment by Deokishisu** [comment]
Didn't see that a similar issue had been closed. My bad.
