### ISSUE TITLE
Monitor Files for Changes

### ISSUE THREAD

**Issue by garakmon** [huderlem/porymap#142]
One suggestion that has been thrown around in the discord is to have a sort of "reload project" or "reload files" action. When the user changes a file while they are in porymap, it might be nice to be able to detect this and ask to reload certain things from disk.

I came across this https://doc.qt.io/qt-5/qfilesystemwatcher.html so I wanted to make a note of it here.

**Comment by tustin2121** [comment]
I'd like to second this. As of right now I have to restart porymap entirely every time I pull from my repo or risk undoing work that was just pulled down.

**Comment by garakmon** [comment]
c0674d96769e62d73181d717c5b76fc931612841
