### ISSUE TITLE
Exporting "Secondary Tiles Image" with a new tileset creates a broken .png

### ISSUE THREAD

**Issue by vexio** [huderlem/porymap#145]
**Using:** pokeemerald
**porymap ver:** 1.2.2

As the title says, exporting a Secondary Tiles Image with a newly created Tileset creates a broken `.png` file.

When the PNG is attempted to be opened, Photoshop says: "Invalid IHDR data"
I'm able to open any other global/primary tileset via Photoshop.

**GIF Example:**
![](https://i.imgur.com/BEU2XkT.gif)

In the attachments will be the palette file I'm using and the indexed house tile I'm attempting to use in my tileset.

[download: secondary tileset porymap issue.zip](https://github.com/huderlem/porymap/files/3414425/secondary.tileset.porymap.issue.zip)

**Comment by garakmon** [comment]
7a239fafda6b348a6b5f1a68f76d1fad1d7e7588
