### ISSUE TITLE
Add different mouse-tool buttons in the Events tab

### ISSUE THREAD

**Issue by Rangi42** [huderlem/porymap#146]
The Map tab has: Pencil, Pointer, Bucket, Eyedropper, Move, and Map Shift. The Events tab basically always uses Pointer (except of course it has events for the pointer to click or drag, instead of doing nothing). At least the Move tool would be useful there, and possibly Map Shift too, to realign the events after doing the map.

Also, taking advantage of the other mouse buttons would be helpful. Even if the toolbar buttons remain for users who just have left-click. The Move function would be useful in all modes; middle-drag or right-drag could do that. (There's the scroll wheel, but some mice don't have one, or just scroll vertically.) Likewise the Pencil, Bucket, and Eyedropper tools would be faster to use if they didn't all need a mode-switching button click or key press.

**Comment by garakmon** [comment]
f6cdd700b8105a8b0b2697ff0b46b21c6eb5543b
