### ISSUE TITLE
Allow a fourth metatile layer type

### ISSUE THREAD

**Issue by Rangi42** [huderlem/porymap#147]
Currently the metatile layer types are hard-coded: 0 is middle/top, 1 is bottom/middle, 2 is bottom/top. In lieu of complete triple-layer tile support in porymap itself, it could at least support a layer type 3, and rely on the user to have modified their project to support that layer type.

(It's pretty simple to do so in the [old way](https://www.pokecommunity.com/showthread.php?t=352725) of having a "burner block": just edit src/field_camera.c:DrawMetatile to have a `case 3` that fills `gBGTilemapBuffers1`, `gBGTilemapBuffers2`, *and* `gBGTilemapBuffers3` from `metatiles`. And of course `metatiles[8]` to `metatiles[11]` would be reading from the subsequent "burner ~~block~~ metatile". Edit: Or use `metatiles[12]` to `metatiles[15]` of the subsequent block so that it can be useful on its own by giving it a sensible bottom layer.)

**Comment by huderlem** [comment]
triple layer is now supported.
