### ISSUE TITLE
Investigate improving map loading speed

### ISSUE THREAD

**Issue by garakmon** [huderlem/porymap#165]
Seems like a lot of work is being done twice, maybe this is avoidable. Would improve map load speeds.

Something to do at a later date.

**Comment by huderlem** [comment]
Maybe related to Editor::displayMap() being called extra times, or maybe populating comboboxes is slow.  Who knows.

**Comment by huderlem** [comment]
The low-hanging fruit has been taken care of with:

- f6c86e0eedad23719fd05474e9ba8392853554c2
- 81cd43933b8c10c49e56b4a509023b5971fbe1c8
- 2f533a86b2aabd76ba65d68da05e80c0fd02d973

These were all issues related to unnecessarily redrawing or even parsing data files from disk.  After eliminating these basic redundancies, load times are down to ~1 second.  Tileset saving times are also down to that same speed.
