### ISSUE TITLE
Exporting a Secondary Tileset exports the incorrect dimensions

### ISSUE THREAD

**Issue by vexio** [huderlem/porymap#169]
With 2.0.0, "Export Secondary Tiles Image...", the images exports in `128x88`, _wxh_, instead of `128x256`.

I believe the reason is because of all the empty space below the secondary tileset, as seen in the screenshot below:
![porymap_10-24-19=444d1](https://user-images.githubusercontent.com/20468242/67541136-b85dd900-f69c-11e9-8ff0-7cca4e79b0a7.png)

**Comment by garakmon** [comment]
Do all of the non-empty tiles exist in the exported image? I believe this is the intended behavior.

**Comment by vexio** [comment]
This is a secondary tileset that has something at the bottom
![Photoshop_10-24-19=0c8e6](https://user-images.githubusercontent.com/20468242/67541586-57370500-f69e-11e9-913e-66fa42330317.png)

And this is the one that has the incorrect dimensions
![Photoshop_10-24-19=14c78](https://user-images.githubusercontent.com/20468242/67541631-83528600-f69e-11e9-9d1c-6805b49bab97.png)

If this is intended, I don't believe it should be.

**Comment by garakmon** [comment]
Are both of those images exported from porymap? I want to understand what's going wrong in the second picture.

**Comment by vexio** [comment]
Yes, these are both exported from Porymap 2.0.0

**Comment by garakmon** [comment]
Okay thanks. One last question--is that distorted bit at the bottom of the second picture supposed to be there or did porymap export some garbage in the image?

**Comment by vexio** [comment]
The distortion at the bottom is not a part of the original tileset/image, Porymap exported with that.
