### ISSUE TITLE
Selecting a group of metatiles does not select their collisions

### ISSUE THREAD

**Issue by Diegoisawesome** [huderlem/porymap#173]
When making a map, I often select multiple blocks at once as a template to draw the map with. If they carry collision information, then I would expect that to be copied as well. Currently this does not happen.

**Comment by huderlem** [comment]
cfaf23aa3eeaa793695f45b4939a0520795b18a1

This works for all types of painting, when selecting groups of metatiles from the map area.  (This includes smart paths and flood fill.)
