### ISSUE TITLE
Open / edit layouts with no associated map

### ISSUE THREAD

**Issue by GriffinRichards** [huderlem/porymap#182]
At the moment, to open/edit layouts that don't have an associated map you have to create a dummy map, which clutters the project and is tedious to do for multiple layouts. The ability to open/edit these layouts without having to do so would be convenient

**Comment by huderlem** [comment]
I'm not sure what a good way to do this in the UI would be.  When sorting the map list by layout, perhaps there could be a right-click option to open the layout in "map-only" mode.  This would effectively disable the non-map tabs, but still allow editing and saving all things layout-related.

**Comment by LOuroboros** [comment]
> 
> 
> I'm not sure what a good way to do this in the UI would be. When sorting the map list by layout, perhaps there could be a right-click option to open the layout in "map-only" mode. This would effectively disable the non-map tabs, but still allow editing and saving all things layout-related.

Is there a reason not to do that? :eyes:

**Comment by gruxor** [comment]
Big +1 to this. Just going by the instances of `setmaplayoutindex` in the scripts alone, there are 18 maps in Emerald that use alternate layouts. Notably Route 111, Mirage Island, and multiple (every layer?) layers of Sky Pillar. Instances like #417 seem to mean that there's more than just those, too.

There's essentially second versions of these maps that are entirely invisible/inaccessible in Porymap (other than the Layout View, in which they just show up as empty folders). So you currently have to create a map, copy your changes over from the main layout, manually replace the alternate layout with your new layout in the json (or overwrite the existing layout file in the filesystem), and then delete your extra leftover map data.

I might try to figure out how to implement something to handle this and PR it, but I've never used Qt or C++ (mainly C# and other interpreted languages, but I'm catching on to C pretty fast via pokeemerald). Would really love to see this become a feature one way or another though.

**Comment by tustin2121** [comment]
Discussion in the discord on the layout issue: https://discord.com/channels/442462691542695948/495019188042203147/1015661854225338438

Summary:
- The layout editor could just be the metatile editing tab (currently (mis)named "Map") with other tabs disabled. Everything in the metatile editing tab is editing the layout only anyway. The remaining tabs are editing things associated with the map and not the layout.
- A button should be added to allow changing the map layout. There should be a heuristic that puts layouts that are similarly named to the map near the top of the list, but all layouts should be available.
    - Discussion was had as to whether to restrict it to matching the same size as the current layout. Not sure if a decision was made about it. The layout is what determines the size of the map anyway.
- The layout list already present in porymap could allow editing of a layout without an associated map, likely by right-clicking a layout "folder" and clicking edit from there.
    - Currently, double clicking on a layout folder expands and collapses the folder. This can already be done with the arrow to the side (which, bug, is invisible in the porymap-supplied themes).
