### ISSUE TITLE
Opening project while project already open can cause bugs

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#184]
If you open a project within Porymap while another project is already loaded (say, the same one) the current map stays loaded in but header info and tileset info resets. This is now seen by Porymap as a fresh change, and will be saved if you save the project.

**Comment by GriffinRichards** [comment]
This is especially noticeable switching between pokeemerald and pokefirered. porymap attempt
s to load the last-open map on the new project. If that map exists in both (e.g. `BattleColosseum_2P`) it will succeed but load the data incorrectly (see below). It will also keep config settings that are not overwritten by the new project (this can cause crashes switching from a project with an older config that doesn't have those settings).

<img width="427" alt="corrupt_battle_colosseum" src="https://user-images.githubusercontent.com/25753467/76596039-9641e780-64d3-11ea-8469-066d494978db.png">

**Comment by garakmon** [comment]
c0674d96769e62d73181d717c5b76fc931612841
