### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by GriffinRichards** [huderlem/porymap#191]
<https://huderlem.github.io/porymap/> has been neglected since ~3.0 release.  It's time to update it.

- [x] Scripting API
- [x] Related projects currently has nothing in it.  We could probably add Poryscript, VGMusicStudio, and/or others. 
- [x] pokefirered support, and its differences from pokeemerald/ruby. (e.g. no region map editor, object events, map header, etc.)
- [x] Revisit "Project Files" section
- [x] Heal locations
- [x] Adding new maps
- [x] File monitoring
- [x] Events tab pencil tool
- [x] Settings / Options

**Comment by huderlem** [comment]
Hijacking this issue to compile missing documentation.

**Comment by GriffinRichards** [comment]
Added heal locations to the checklist, apparently those aren't mentioned either. It may also be worth adding a page for the Tileset Editor, which only has a short description in Navigation at the moment. I don't know that the Tileset Editor needs much clarification, but at the moment its description omits features like the Palette Editor.
