### ISSUE TITLE
Allow selection of MAPSEC_NONE tiles in region map

### ISSUE THREAD

**Issue by sjgriffiths** [huderlem/porymap#210]
The region map editor does not allow selection of MAPSEC_NONE tiles in order to potentially change them, requiring direct hex editing of **region_map_section_layout.bin**. I'd suggest this restriction be lifted as I've now seen at least one other bar me wishing to do this.

**Comment by GriffinRichards** [comment]
Already fixed by `141f0fa773783b43bf4a9a0824dec14a3944e789`, duplicate of #203
