### ISSUE TITLE
Can't make the right panel narrower

### ISSUE THREAD

**Issue by lmao-emerald** [huderlem/porymap#214]
![image](https://user-images.githubusercontent.com/18596778/80615364-e05d3900-8a3f-11ea-90e1-7089d6a75933.png)

Since the Porymap 4.0 I can't make the right panel as narrow as it was in the previous release.

Screenshoot of Porymap 3.0.1
![image](https://user-images.githubusercontent.com/18596778/80615511-0f73aa80-8a40-11ea-90ee-c6740c58756e.png)

**Comment by huderlem** [comment]
Resolved in #216
