### ISSUE TITLE
Tabs display incorrectly after failed project open

### ISSUE THREAD

**Issue by GriffinRichards** [huderlem/porymap#221]
This will result in either: A. Lack of main window tabs, which prevents switching off of the current tab, B. Duplicate sets of main window tabs, which aside from being confusing is harmless, or C. porymap will crash.

To reproduce A:
1. Attempt to open a project in porymap that fails to open (e.g. missing a necessary file)
2. File->Open Project and select a project that will open successfully
3. Notice that none of the main window tabs appear

To reproduce B:
1. Attempt to open a project in porymap that fails to open (e.g. missing a necessary file)
2. File->Open Project and select the same project again
3. Notice that the main window tabs have duplicated
4. File->Open Project and select a project that will open successfully
5. Notice that the duplicated tabs persist

To reproduce C:
1. Open a project in porymap that will open successfully
2. File->Open Project and select a project that will fail to open (e.g. missing a necessary file)
3. Porymap will briefly open the project with duplicate tabs and then crash

Both A and B can be resolved by relaunching porymap with a project that will open successfully.

<img width="595" alt="Tabs-missing" src="https://user-images.githubusercontent.com/25753467/81978082-ff8bc700-95f8-11ea-9a27-d777fd01d653.png">
<img width="590" alt="Tabs-duplicate" src="https://user-images.githubusercontent.com/25753467/81978093-0286b780-95f9-11ea-9218-5d78c6608774.png">

**Comment by huderlem** [comment]
Copying discussion from earlier:


That's a larger issue than just the tabs. The way it calls initWindow() upon failed load is deeply flawed
It ends up duplicating instances of connect() on a bunch of Ui, and the whole existing Editor instance isn't cleaned up.

**Comment by garakmon** [comment]
d1af93f3b5083010ca7215f87560993b558cce1f
