### ISSUE TITLE
Suggestion: Add ruler tool

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#228]
This just makes it easier for me to count metatiles. Not too important.

**Comment by huderlem** [comment]
Does the grid overlay satisfy this need?  The cursor rectangle is slightly awkward when interacting with events because it partially covers them up, so you can't see what's underneath.  It's a minor detail either way--it's hard to know which way is best.

**Comment by ketsuban** [comment]
A ruler tool would also solve @Sierraffinity's problem. Being able to measure distance nondestructively would help when scripting movements.

**Comment by huderlem** [comment]
Good idea, but is that any different than pressing `Ctrl+G` to quickly turn on the grid view?  Maybe it is.

**Comment by Sierraffinity** [comment]
Honestly, a ruler tool would be even better. I didn't even consider that as an option.

**Comment by Sierraffinity** [comment]
Relatedly, could the coordinates be shown in the bottom left corner when mousing over the map, like the draw view?

**Comment by huderlem** [comment]
#310
