### ISSUE TITLE
Pokefirered Region Map Editor

### ISSUE THREAD

**Issue by GriffinRichards** [huderlem/porymap#230]
Currently the region map editor is only available for pokeruby/pokeemerald. It needs to be adapted to work for pokefirered. This will probably involve moving some data in that repo, which would be a breaking change.

**Comment by hjk321** [comment]
I happened to be poking around `region_map.c` earlier so I thought I would add my two cents.

The way the four regions in firered (sevii is technically 3 seperate regionmaps) is set up is luckily agnostic to the major differences between the emerald and firered code. I haven't taken a look at how porymap edits emerald or ruby at the moment, but as long as we are currently able to directly edit the mapsecs *within* `region_map.c`, we can essentially use 90% of our current implementation for a firered editor without needing to move anything in pokefirered itself. The only major change is to add a drop down to select *which* of the four region maps to edit, as well as storing four sets of paths/var names for each region map.

**Comment by garakmon** [comment]
works as of d14bcdbdc19d425ac17fd3487c18e0bd2fd5aeff
