### ISSUE TITLE
Linux build issue with 4.0.0 and on

### ISSUE THREAD

**Issue by Seldon2066** [huderlem/porymap#235]
I'm running Linux Mint and the latest version I can successfully build is 3.0.1. I followed identical steps to try to install 4.0.0 and 4.0.1 but the make returns an error after a wall of text saying that "recipe for target 'event.o' failed". Maybe I am doing something wrong but it works with 3.0.1

**Comment by garakmon** [comment]
porymap requires Qt version 5.14 or later to build do you have that or are you able to update?

**Comment by Seldon2066** [comment]
I have 5.9.5 which I believe is the most up to date.

**Comment by nicholatian** [comment]
5.9 < 5.14. Update Qt and re-attempt.

**Comment by Seldon2066** [comment]
Yep. As I said stupid. I must be really tired to take that long to notice that. I'm updating Qt and I'm going to try again tomorrow.

**Comment by Seldon2066** [comment]
I updated Qt to 15.0 and it now builds successfully however when I try to open pokefirered it says it can't find "pokefirered/include/constants/secret_bases.h" which is a file that doesn't exit in pokefirered but does in pokeemerald (which opens successfully). Is there some setting I have to change to use pokefirered?

**Comment by garakmon** [comment]
In the porymap.project.cfg file that exists in your pokefirered folder, check the value of the base_game_version setting

**Comment by Seldon2066** [comment]
That was it. Thanks.
