### ISSUE TITLE
Map search filter incorrect when sort type is changed

### ISSUE THREAD

**Issue by GriffinRichards** [huderlem/porymap#244]
Search result folders are automatically collapsed if the Sort By type is changed, and the search results are limited to matches in folder names. When switching to Sort By Group with an active search this commonly yields no search results.

Example: Type "petalburg" in the map list search bar and switch between sort types. Upon switching to Area/Layout the result folders will be collapsed, and switching to Group will yield no results. The search results can be corrected by updating the search bar, e.g. by deleting the "g" in petalburg.

It would also be convenient if the currently selected map had its folder expanded on switching sort types. Unclear if this was a regression or not

**Comment by huderlem** [comment]
Fixed by b58ec89
