### ISSUE TITLE
Magic fill bug/optimization

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#247]
For magic fill, you do Ctrl+MiddleClick, and sometimes I accidentally roll the wheel and it ends up zooming in. This should be prevented.
Also, magic fill should not execute if the metatile being filled matches the one currently selected (if there is only one metatile selected of course).

**Comment by huderlem** [comment]
370221a974ce26bb6fd51c5d0faeb82c31226017
73921052970fb4416a25d037c88466a801092ef0
