### ISSUE TITLE
Ctrl+Shift+Z does not redo in tileset editor

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#250]

**Comment by huderlem** [comment]
I don't understand this Issue.  Why would you expect `Ctrl+Shift+Z` to undo in the tileset editor?  `Ctrl+Z` is the undo shortcut.

**Comment by Sierraffinity** [comment]
My bad, I meant _redo_. In the regular map editor, Ctrl+Y and Ctrl+Shift+Z both redo, and the latter is really handy to use.

**Comment by huderlem** [comment]
Gotcha.  I didn't even know Ctrl+Shift+Z worked for redo in the map area

**Comment by Sierraffinity** [comment]
I think I added it ages ago, actually.

**Comment by huderlem** [comment]
cc16440
