### ISSUE TITLE
Suggestion: Keep focus on the currently selected tile when zooming in the map view

### ISSUE THREAD

**Issue by River707** [huderlem/porymap#256]
I tend to use ctrl+scroll to zoom when working on a map. It would be nice if the currently selected tile, i.e. the one the mouse cursor is currently hovering over, was kept in focus when zooming. This is a fairly common feature in many image editors, and it seems like it would be a good addition to porymap.

**Comment by huderlem** [comment]
We tried doing this in the past, but it turned out to be more difficult that anticipated.  It's a very desirable feature, though, so we should try again.
