### ISSUE TITLE
Suggestion: Sync selected metatile between tileset editor and map editor

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#257]
This would make it easy to find a metatile on the map and edit it without having to go hunt for it.

**Comment by Sierraffinity** [comment]
This now has the side effect of changing the currently selected metatile in the tileset editor when saving the tileset (as it reloads the map and presumably the selected metatile with it).

**Comment by GriffinRichards** [comment]
Yeah oddly enough it's because refreshing the map updates the metatile zoom, and updating the zoom is considered updating the metatile selection. I don't think the zoom needs to do this
