### ISSUE TITLE
QoL Suggestions for the Tileset editor

### ISSUE THREAD

**Issue by CodexKraken** [huderlem/porymap#260]
- [x] Add a button to toggle a grid for the tile set editor
- [x] A zoom slider _inside_ of the editor like the one that is available in the mapping view 

The following I dont know if its possible, but it would be amazing:

- [x] Revertible palettes, once you import a palette, it overwrites right away, a feature to not overwrite the palette until you save would be nice

**Comment by Meister-anon** [comment]
A grid on the tile set would be extremely helpful.

also maybe a button to revert all map changes to its default state?

Changed the secondary  tileset for a map once and had to spend the next 10 minutes trying to figure out what it originally was, after all the buildings got glitched out.

**Comment by GriffinRichards** [comment]
Updated original comment to a checklist. Grids for the Tileset Editor added in 5.2.0

**Comment by GriffinRichards** [comment]
Zoom sliders added in #582

**Comment by GriffinRichards** [comment]
Idk if the last problem was never true or if it was changed at some point, but it's not a problem currently. Imported palettes aren't written to the project until the user saves their changes in the Tileset Editor.
