### ISSUE TITLE
Suggestion: Add Map Frame option to New Map Dialog

### ISSUE THREAD

**Issue by SethBarberee** [huderlem/porymap#262]
(pokeemerald) 
Some explanation is probably needed. When you enter a new map, a display will popup in the top left. This frame is changed in `src/map_name_popup.c`. I created a map in porymap and didn't know to modify this file to account for my new map section so I saw the name of the map and a garbled mess for the frame. Once I added the line, everything was perfect. It would be nice if porymap did this upon map creation. If I find some free time, I might look into implementing this. 

My idea for how it would work:
* When creating a new map, an dropdown labeled `Map Frame Theme` will be on the dialog. (options for this dropdown are populated by the enum at the top of the file)
* A new map section will be added at the end of the `gRegionMapSectionId_To_PopUpThemeIdMapping` array.

**Comment by huderlem** [comment]
Good catch.  The implementation idea is a bit iffy, though.  It's not in porymap's best interest to modify C files with actual functions etc..  I would consider these options:
1. Split that array into its own file, similar to `src/data/heal_locations.h`.
2. Simply inform the user with a message box whenever they create brand new map sections.

I sort of prefer number 2, as it's less invasive and won't spectacularly fail as soon as someone decides to customize their map name popup code.

**Comment by SethBarberee** [comment]
True, Option 2 does seem like a good idea. I think documentation should also be updated in the `Adding a New Map` section to tell the user too. Just to cover our bases on all sides. I haven't done much hacking in pokefirered/pokeruby to verify if the format is the same. I'll make sure and then PR a doc update at least.

**Comment by GriffinRichards** [comment]
I'm in the middle of redesigning the New Map dialog, I'm going to say this probably isn't worth doing anything about on Porymap's end.

This feature is only present in pokeemerald, and the array in question can be updated to use an appropriate size constant (so that as `MAPSEC` values are added they'll be given a default value of `0`, rather than reading outside the array), after which I don't think we need to alert users that the feature exists.

**Comment by GriffinRichards** [comment]
> the array in question can be updated to use an appropriate size constant

Array will be updated in pokeemerald by https://github.com/pret/pokeemerald/pull/2063
