### ISSUE TITLE
Event tab issues

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#264]
- [ ] You can't scroll through events using the arrow keys on the spinner since focus is lost each time a new event is loaded.
- [x] Dropdown indexes get reset to 0 despite having new text, so using the arrow keys on those will go to the wrong next item in the list.

**Comment by huderlem** [comment]
@Sierraffinity You'll have to be more clear about that second bullet point.  I can't tell what it means.

**Comment by Sierraffinity** [comment]
Go to an event in the event tab and click in the "Sprite" dropdown box. If you click on the arrow once, the dropdown will start at index 0 (ANABEL), and if you click in the textbox and then hit the down arrow key, it'll jump to index 1 (ARCHIE) as if it was previously on ANABEL. This same behavior occurs for all dropdowns.

**Comment by GriffinRichards** [comment]
It's possible the behavior for that first bullet point has changed since this was opened. With my mouse over any part of the ID spinner I'm able to scroll through the events without it losing focus.

**Comment by Sierraffinity** [comment]
I meant having the spinner selected then using the arrow keys on the keyboard to move up and down. At the time, each new event loaded meant that a new spinner would be created for it, and keyboard focus would be lost.
