### ISSUE TITLE
Suggestion: Allow manual entry of RGB Values in Tileset Palette Editor

### ISSUE THREAD

**Issue by vexio** [huderlem/porymap#267]
Instead of using the sliders (which can be annoying to fine-tune sometimes, or even more annoyingly to swap two color slot values), allow the user to click to the right of the RGB Value slider and manually enter a number for each value. 

![porymap_hvyvc1MGY7](https://user-images.githubusercontent.com/20468242/86691284-89369000-bfbd-11ea-877d-5d9cc4fc8048.png)

Obviously, if the entered value is not divisible by 8 (or is 0), it will round up/down to the nearest valid number.

**Comment by aaaaaa123456789** [comment]
Ideally, instead of a simple "divide by 8" conversion, the program could do the proper conversion (multiply by 31, divide by 255, round to nearest).

> Obviously, if the entered value is not divisible by 8 (or is 0), it will round up/down to the nearest valid number.

0 is both valid and divisible by any integer other than itself, including 8.

**Comment by vexio** [comment]
> 0 is both valid and divisible by any integer other than itself, including 8.

Right right, that was a misplacement/typo. Meant to say 0 would be an exception.

**Comment by aaaaaa123456789** [comment]
> > 0 is both valid and divisible by any integer other than itself, including 8.
> 
> Right right, that was a misplacement/typo. Meant to say 0 would be an exception.

Why?

**Comment by SBird1337** [comment]
`rgb5 = round((rgb * 31) / 255)` works for every integer in the given interval [0;255]
