### ISSUE TITLE
Display berry tree sprites and copy AMap behavior with Secret Base signposts

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#27]
Berry tree sprites show the generic entity sprite instead of the correct berry tree.

AMap treats Secret Base signposts as warps when doubleclicking them to go to the appropriate Secret Base map. This should be copied for QoL into porymap.

**Comment by Deokishisu** [comment]
Hipster is also showing as a generic entity sprite like the berry trees. I believe that AMap actually renders those correctly.

**Comment by huderlem** [comment]
I don't think porymap should try to be smart and hardcode logic about event objects that use dynamic sprites.  However, it could potentially introduce a new configuration setting that specifies a base sprite to show for various dynamic sprites.

**Comment by huderlem** [comment]
Closing--I don't think anything like that will happen.  If it does, a different Issue will be used.
