### ISSUE TITLE
Following a warp causes a bugged "Selection" tile.

### ISSUE THREAD

**Issue by BigBahss** [huderlem/porymap#284]
Double clicking a warp event to go to that location will cause the selection tile to lose 3 of it's quadrants, like in the screenshot. Selecting a new tile doesn't fix it, only re-opening porymap.
Edit: This also occurs when double clicking a map connection under the connections tab.

![porymap_tile-selection-bug](https://user-images.githubusercontent.com/58710639/90229284-a4c75e80-dde5-11ea-9e02-70f523372696.png)

**Comment by garakmon** [comment]
I can't reproduce buggy behavior. What metatile(s) did you have selected pre-map change, and how did you select them?

**Comment by BigBahss** [comment]
Seems to happen for any metatile whether I select it from the tileset or from the map. Even when I don't select any metatile after opening porymap and just leave the transparent (black) tile selected and follow a warp it still occurs. While testing it with other tiles I also noticed that the remaining quadrant is actually the bottom-right, now shifted to top-left. I wonder if this is specific to Linux?

After typing this I figured I should try removing my porymap.cfg to see if that would fix the issue, it did not although it changed the behavior and only shifted the metatile a little bit:
![porymap_tile-selection-bug_2](https://user-images.githubusercontent.com/58710639/90317000-4d63e400-def4-11ea-8fac-adc350bdc723.png)

**Comment by BigBahss** [comment]
This looks like it's a me issue. I tried with a clean build on my other computer and it works just fine. Then I tried running that same binary on the first computer and its bugged again.

**Comment by Sierraffinity** [comment]
I've noticed this weird behavior myself, though I don't know what triggers it exactly. Definitely not just you though.

**Comment by GriffinRichards** [comment]
The selection still doesn't update correctly when switching between maps with different primary tilesets, I don't know if that's related. I also can't reproduce the specific issue with the selection changing size (macOS)

**Comment by garakmon** [comment]
Okay I can reproduce this on all platforms by zooming the metatile selection view

**Comment by garakmon** [comment]
2e077b45c784cf263cfb188c48055f3ab13888ba
