### ISSUE TITLE
Player View Overlay

### ISSUE THREAD

**Issue by Pyredrid** [huderlem/porymap#289]
When making maps, there's often a need to "hide" certain transitions and ugly spriting from the player somewhere they can't see.  Like mapping out some cliffs on one edge of the map where the border is a bunch of trees.

Being able to toggle what the player can/cannot see based on the current collision of the map would be extremely helpful for hiding these transitions in the mapping workflow.

**Comment by garakmon** [comment]
is putting the cursor (when the player view rectangle is enabled of course) over the reachable blocks not sufficient?

**Comment by Pyredrid** [comment]
While it would be nicer, the player view rectangle is enough.  also, i'm dumb for not looking harder for a feature like that.

**Comment by garakmon** [comment]
I think this is best accomplished via the scripting api, so I'm closing this.
