### ISSUE TITLE
Selection to another Maps not able

### ISSUE THREAD

**Issue by Dragonflysots** [huderlem/porymap#291]
You can't copy some part of Maps in Selection to copy in a another Map. In older version was this able.

![unknown](https://user-images.githubusercontent.com/27623565/91633610-27593c00-e9ea-11ea-9270-2b64c40adc2e.png)
![unknown-1](https://user-images.githubusercontent.com/27623565/91633612-288a6900-e9ea-11ea-9e95-61a175f90584.png)

**Comment by BigBahss** [comment]
The commit that broke this functionality is 79e384ef76b2c6ff855b473057db7663591720bc
