### ISSUE TITLE
Metatile shows in Porymap but not in game (Firered with VBA emulator)

### ISSUE THREAD

**Issue by JoJoCrusade** [huderlem/porymap#298]
I tried to expand the tileset png for the generic building 1 file to include a different video game system sprite.

I opened the original tiles in Galebrowser, expanded the canvas size, imported the pallet and drew in my new sprite work. 
![tiles](https://user-images.githubusercontent.com/66278471/92045615-0a589c00-ed4f-11ea-9ef6-1b12bb61aad1.png)

My new art showed up correctly in Porymap. I edited the Generic Building 1 tileset and imported my new larger file tileset.png.
This let me make my new metatiles with my added art. 
![porymapbug](https://user-images.githubusercontent.com/66278471/92045687-2b20f180-ed4f-11ea-905a-98da0400a7db.PNG)

The issue is once I get in game it doesn't render my new metatiles correctly
![vgbsnip](https://user-images.githubusercontent.com/66278471/92045718-3aa03a80-ed4f-11ea-96d6-07cba7dae22f.PNG)

Is the error on my end? Can I not just resize the tileset canvas? Creating a brand new tileset and importing the same tileset png to it seems to work instead, but I would prefer to have to remake all the other metatiles that make up the bedroom.

**Comment by garakmon** [comment]
In order to produce a matching ROM, there are some make rules defined in [tileset_rules.mk](https://github.com/pret/pokefirered/blob/master/tileset_rules.mk) that limit the tilesets to a certain number of tiles. You can go ahead and delete these rules and rebuild and the problem should be gone.

**Comment by ShinyDragonHunter** [comment]
It is recommended to NOT use VBA either. M-GBA is a popular suggestion. 
I, myself, use the Bizhawk Emulation Suite with the M-GBA core

**Comment by JoJoCrusade** [comment]
Thanks for the help! Sorry for asking a seemingly dumb question to being with. I’ll switch emulators as well, but all of the sudden I’m having (non Porymap) issues building firered at all so I haven’t been able to test the fix. Im sure that’s all it was though
