### ISSUE TITLE
Cleanup large log files

### ISSUE THREAD

**Issue by huderlem** [huderlem/porymap#307]
Currently, Porymap writes to a single log file, which grows infinitely over time.  We should probably have it clean up after itself when the file becomes too large.  Maybe Porymap is launched, it checks if the log file is greater than 20MB and clears the contents of the file.  I don't think we care about getting any fancier than that, since previous log content is not important.  Users pretty much only care about the log for recent errors.

**Comment by BigBahss** [comment]
Maybe instead of simply clearing it we get rid of the first half of it so that recent logs are retained.

**Comment by huderlem** [comment]
Maybe, but there is no reason to complicate it.  These logs are not important, except for error troubleshooting.
