### ISSUE TITLE
Porymap can crash after switching maps with the palette editor open

### ISSUE THREAD

**Issue by GriffinRichards** [huderlem/porymap#308]
The palette editor remains open if you switch to a new map but evidently does not always update correctly
1. Open palette editor
2. Switch to a new map
3. Try to change the palette id

**Comment by BigBahss** [comment]
This crash is difficult to recreate consistently. Sometimes it crashes, and then closing/opening porymap to try those steps again won't crash it. I also noticed it won't always crash on the same line of code.

**Comment by BigBahss** [comment]
Relatedly, when changing the palette id with the spin-box buttons, it will actually change the id by 2, and is very slow to do so. This happens whether you switch to a new map or not. This might be worthy of its own issue, or for a general "Palette editor overhaul" issue.

**Comment by Deokishisu** [comment]
I can reproduce this crash semi-consistently with pokefirered. Here are the steps. I don't know if this matters, but make sure your last loaded map was Kindle Road.

1. Open porymap. It should open to Kindle Road.
2. Open the tileset editor.
3. Open the palette editor.
4. Scroll to palette number 07.
5. Close the palette editor, then the tileset editor.
6. Switch maps directly to the Player's House 1F map.
7. Open the tileset editor.
8. Open the palette editor. It should already be on palette 07.
9. Close the palette editor, then the tileset editor.
10. Switch maps directly back to Kindle Road.
11. Open the tileset editor.
12. Open the palette editor. It should already be on palette 07.
13. Try to scroll down on the palettes by clicking the down arrow with your mouse.
14. The program should (sometimes) now crash without leaving a log.
