### ISSUE TITLE
Porymap messes some things up and doesnt show some things

### ISSUE THREAD

**Issue by mertens2** [huderlem/porymap#315]
I dont really know why, but it does. Whenever i open it and save my changes, i have to go to those files and restore them to what they were before the changes were applied.
Also, Porymap doesn't seem to load the data correctly, and sets "heal_locations.h" to a weird "empty" that has a different estructure than the original file...
I just pulled the last update of my pokeemerald and im fixing the conflicts, but i dont really want to keep fixing those files.
It also does not load any gfx sprite and it settes some of the gfx's of petalburg city to "event_obj_gfx".

**Comment by garakmon** [comment]
Can you tell us: 
1. What version of porymap are you running? (you can find this out in the About window)
2. How old is your project and what is the latest commit from pokeemerald that it has? In the CHANGELOG.md file, there is a list of breaking changes introduced with each major version release that could be causing this.
* If [Pok-mon-Gems](https://github.com/mertens2/Pok-mon-Gems) this is the project you're working on and is up to date, I can take a look myself.

**Comment by mertens2** [comment]
1 I have the lastest Porymap version
2 Trying to update it has broken the project so i went back to the last commit i uploaded to the [https://github.com/mertens2/Pok-mon-Gems](url) repository.
Anyways, the way it replaces "src/data/heal_locations.h" is weird, because it doesn't have that syntaxis even in the lastest pokeemerald commit...

**Comment by mertens2** [comment]
Fixed the healspot things, but it still doesnt show the sprites

**Comment by garakmon** [comment]
you are missing changes from this PR here: https://github.com/pret/pokeemerald/pull/1010 that are necessary for porymap to function correctly

**Comment by mertens2** [comment]
ok, thanks
it didn't make porymap show the sprites but at least it works more stable now

**Comment by GriffinRichards** [comment]
You're missing additional breaking changes from this PR: https://github.com/pret/pokeemerald/pull/910
Note for instance the changes to directory names
