### ISSUE TITLE
Show total % breakdown of wild Pokémon on a map

### ISSUE THREAD

**Issue by MandL27** [huderlem/porymap#333]
On the Wild Pokémon tab, show the total encounter rate and level range of a given species across all slots mapped to them. This would help to visualize encounter chances.

**Comment by hjk321** [comment]
I'll go ahead and take on this one. Would a different color percentage in parentheses do the trick?

Another thing I'll fix in the meantime is that the `land_mons`, 'water_mons`, etc is exported to json in a seemingly arbitrary order which causes messy diffs, so I'll get it to export in alphabetical order to keep it consistent.
