### ISSUE TITLE
File > Close Project

### ISSUE THREAD

**Issue by ProjectRevoTPP** [huderlem/porymap#34]

**Comment by garakmon** [comment]
Is the idea here that closing a project will close the application, and when opening the app again will not look for the project at that path? Or is the idea more like it will un-load the current project in the editor and it will be like there is no project open (how it is on first use), and if you close from this state it will not try to reopen last project folder?
I hope that makes sense.

**Comment by garakmon** [comment]
c0674d96769e62d73181d717c5b76fc931612841
