### ISSUE TITLE
[Feature Request] Ability to copy certain event objects

### ISSUE THREAD

**Issue by LOuroboros** [huderlem/porymap#340]
I'm not sure if it's feasible, but I figured it wouldn't hurt to bring it up.

It'd be nice, assuming that it's possible at all, to make PoryMap have the ability of creating copies of existing event objects *(like for example the Youngster in Route 101 or a signpost script added to the map)* so you can paste them somewhere else, be it on the same map or a different one.

**Comment by GriffinRichards** [comment]
This exists somewhat already, Ctrl+D will duplicate selected events. It won't let you copy them to other maps, however.

**Comment by GriffinRichards** [comment]
I don't remember if this was added subsequently or if it existed at the time, but this is currently a feature. Events can copied with `Ctrl+C`/`Edit->Copy` and pasted to the same map or a different map with `Ctrl+V`/`Edit->Paste`.
