### ISSUE TITLE
Crash when trying to add map to nonexistent group

### ISSUE THREAD

**Issue by hjk321** [huderlem/porymap#355]
**Steps to Reproduce:**
* Tools > New Map
* Put a garbage string in for map group
* Press confirm

Tested with pokefirered on macos, but should (probably) be reproducible regardless.

**Suggested solution(s):**
* Turn map group setting into a drop-down with valid strings
* Validate data before trying to do stuff with it lol

**Comment by BigBahss** [comment]
Yeah that box shouldn't have been editable. Now you can only select groups from the drop-down.
