### ISSUE TITLE
Automatically position a newly-added event to the center of the current viewport

### ISSUE THREAD

**Issue by hjk321** [huderlem/porymap#358]
As of right now, any added event goes to x:0 y:0, which on moderate-to-large sized maps means you have to constantly drag the event to where you needed. A good enhancement would be to place the event at the part of the map you are "looking" at. For example, if you're zoomed in on the bottom right corner of the map, the new event would be placed at x:30 y:45 or wherever.

This should be fairly easy to implement. The only potentially complicated part is determining the current "view" of the map screen to get the correct coordinates from.

**Comment by BigBahss** [comment]
Does using the pencil tool to 'paint' the events onto the map solve this issue?

**Comment by hjk321** [comment]
Yes, but since that behavior isn't as apparent to users as a big green "add object" button, this would still be a nice enhancement to have.

**Comment by BigBahss** [comment]
I agree, it isn't super obvious that you can use the pencil to do this. And since there are 2 methods to add events, they should both work well.
