### ISSUE TITLE
Handle UNC paths

### ISSUE THREAD

**Issue by lorissa-b** [huderlem/porymap#363]
Trying to use a UNC path (like, for example, grabbing the project folder from a WSL install) results in it completely failing to locate the specified folders.

Instead of opening `\\wsl$\Arch\<user>\home\pokeemerald` as instructed, Porymap tried to open `Arch\<user>\home\pokeemerald`.

**Comment by huderlem** [comment]
This is supported in the latest release (4.5.0).  Upgrading to Qt 6 provided the fix.
