### ISSUE TITLE
Not Working Semi-transparency Background Display on Porymap

### ISSUE THREAD

**Issue by Dragonflysots** [huderlem/porymap#366]
Pokemon Sovereign of the Skies currently uses a javascript to display specific backgrounds (BG3) for semi-transparency. Version 4.0.0 was still able to do this, but the current build does display the correct layout. (Say we put the BG3 over BG1), but the alpha channel display (transparency) does not work properly anymore.

Version 4.0.0:
![image](https://user-images.githubusercontent.com/27623565/115457114-5136cb80-a224-11eb-9cd1-77c5450755d8.png)

Current Version:
![image](https://user-images.githubusercontent.com/27623565/115457155-5f84e780-a224-11eb-96c6-66c1353ac21f.png)

Javascript:
```
export function SetStandard(){
    map.setMetatileLayerOrder([0, 1, 2])
    map.setMetatileLayerOpacity([1.0, 1.0, 1.0])
    map.redraw()
}

export function SetBG3AlphaAboveBG1(){
    map.setMetatileLayerOrder([1, 2, 0])
    map.setMetatileLayerOpacity([0.5, 1.0, 1.0])
    map.redraw()
}

export function SetBG3AlphaAboveBG2(){
    map.setMetatileLayerOrder([1, 0, 2])
    map.setMetatileLayerOpacity([0.5, 1.0, 1.0])
    map.redraw()
}

export function SetBG1AlphaBG3AboveBG2(){
    map.setMetatileLayerOrder([1, 0, 2])
    map.setMetatileLayerOpacity([1.0, 1.0, 0.5])
    map.redraw() 
}

export function onProjectOpened(projectPath) {
    map.registerAction("SetStandard", "Standard")
    map.registerAction("SetBG3AlphaAboveBG1", "BG3 Alpha > BG1 > BG2") 
    map.registerAction("SetBG3AlphaAboveBG2", "BG1 > BG3 Alpha > BG2") 
    map.registerAction("SetBG1AlphaBG3AboveBG2","BG1 Alpha > BG3 > BG2")
}
```

**Comment by garakmon** [comment]
Confirmed to have been a build issue and is fixed by Qt 6.1
