### ISSUE TITLE
Suggestion: Remember the last settings used for creating a New Map

### ISSUE THREAD

**Issue by sphericalice** [huderlem/porymap#377]
Title is pretty self-explanatory, I think it would be nice if the new map dialog remembered the last configuration used, this would be helpful when e.g. creating a lot of floors for a dungeon that share the same mapsec, music, running/biking settings, etc.

**Comment by GriffinRichards** [comment]
Should this be session-specific? i.e. I think there's some value in restoring the defaults in the new map window.

**Comment by sphericalice** [comment]
Yes I think session-specific is all that's needed, at the time I was porting maps from my ROM hack and it got annoying having to re-set for example the settings for an entire city's indoor maps when they would share most if not all of the settings. I don't think anything would be really gained by it saving between sessions (and I imagine that would probably be harder to implement, probably?)

**Comment by garakmon** [comment]
agree
