### ISSUE TITLE
Porymap delete random Eventscripts

### ISSUE THREAD

**Issue by Dragonflysots** [huderlem/porymap#380]
For some reason, scripts are constantly being deleted somehow or assigned completely wrong entries. I have fixed this about 20 times now and it happens again and again.

![image](https://user-images.githubusercontent.com/27623565/133897337-1986d2d2-aa49-432e-8aeb-8ae9f895d83e.png)

This happens completely randomly when saving and closing and reopening.

**Comment by GriffinRichards** [comment]
It was determined this is an issue with the global script autocomplete, added [in this commit](https://github.com/huderlem/porymap/commit/3ccf433d1eb33e4e82419da016fb39ab8b146a8d). This is the dropdown that appears when you begin typing in a `Script` box.

For now (until it's fixed), the workaround is to not select any scripts from the global autocomplete. You can still type out the name of a script, copy/paste the name of a script, or select a script from the list of **local** scripts by expanding the dropdown manually before you begin typing.
