### ISSUE TITLE
How do you export

### ISSUE THREAD

**Issue by MrJoeJeff** [huderlem/porymap#385]
I made a project but i dont know how to play it on an emulator or GBA

**Comment by huderlem** [comment]
Porymap doesn't export a game ROM.  Instead, it works with the gen 3 decompilation projects.  See their documentation for help building the ROM.  e.g. https://github.com/pret/pokeemerald

**Comment by MrJoeJeff** [comment]
so you cant play it?

**Comment by LOuroboros** [comment]
> 
> 
> so you cant play it?

Play what? This is a map editor.

What you normally do is to `git clone` a decompilation project *(Pokeruby, Pokefirered or Pokeemerald specifically)*, open Porymap, open your decompilation project's folder on it, make whatever changes you want, File -> Save, and then build a ROM like you'd normally do by using `make`.
