### ISSUE TITLE
Install specific Qt version

### ISSUE THREAD

**Issue by gorka3reta** [huderlem/porymap#386]
I am trying to install porymap following the INSTALL.md instructions for Linux (I am using Ubuntu 20.04.3 LTS) but if i execute the command to install qt, the version 5.12.8 is installed by default, how can i change the command in order to get the requiered version of qt?

**Comment by huderlem** [comment]
You'll need to manually install the desired version.  You can consult official Qt documentation for that. https://doc.qt.io/qt-6/gettingstarted.html
