### ISSUE TITLE
Issues with compiling from source on releases after 3.0.1

### ISSUE THREAD

**Issue by somedamnauthor** [huderlem/porymap#400]
Hello, following the instructions in order to compile from source, I'm running into a few errors when I run the `make` after `qmake`. Tried all releases from the latest until it worked with 3.0.1

Here is the stdout from the `make`  - https://pastebin.com/aBQdxEeX

This seems to be the first of the errors

![image](https://user-images.githubusercontent.com/77018843/148326533-f33d6b5a-6b12-4f9f-9764-d2eb789302c6.png)

Apologies if I have some basic issues with my setup, I'd love to know if so.

**Comment by GriffinRichards** [comment]
Check your qt version with `qmake --version`.
Per the installation instructions, qt version >= 5.14.2 is required (though I believe >= 5.14.0 at least will work).
<https://github.com/huderlem/porymap/blob/master/INSTALL.md>

**Comment by somedamnauthor** [comment]
Thank you! It had initially installed Qt 5.12.8. I then installed 5.14.2, took me an embarrassingly long time to figure out how to have qmake use the newer Qt version, but it's working now!
