### ISSUE TITLE
Memory crash on Mac Os

### ISSUE THREAD

**Issue by xirosrh** [huderlem/porymap#406]
I downloaded version 4.5.0 for Mac OS (i'm using Mac OS Catalina 10.15.7), and when i try to open porymap it won't start (application not responding) and finally there is a memory crash.

Porymap 4.4.0 works perfectly.

**Comment by GriffinRichards** [comment]
Do you have a crash log? I'm on macOS 10.13 so I can't personally test release version 4.5.0, but I can't reproduce any crashes when I launch Porymap 4.5.0 built from source.

**Comment by xirosrh** [comment]
How can i search for the crash log?

**Comment by GriffinRichards** [comment]
When Porymap crashes you'll get a "porymap quit unexpectedly" popup. If you select "Report..." that will open the crash log. Alternatively launch "Console" and look for the dated report for Porymap under User Reports.

Once it's open the most relevant bit of the log will be under the section `Thread 0 Crashed`

**Comment by GriffinRichards** [comment]
A few other people on macOS have had issues launching 4.5.0. It seems [this issue](https://github.com/huderlem/porymap/issues/378) is still occurring for some environments. I can't tell if this is your issue as well without more information, but assuming it is here's 3 options for you:
1. Disable Porymap's wild encounters tab (set `use_encounter_json` to `0` in your project's `porymap.project.cfg` file).
or 2. If you don't want them, delete the additional wild encounters for Battle Pyramid and Battle Pike.
or 3. Wait for the next release
If you do either 1 or 2 you can undo this when you start using the next release.
