### ISSUE TITLE
[Feature Request] Make Porymap read "in connection" events/Clone Objects implemented in Pokeemerald projects

### ISSUE THREAD

**Issue by LOuroboros** [huderlem/porymap#409]
So, Pokémon FR/LG have this feature where an event object may have a clone outside of the boundaries of a map, meant to serve as a bridge to keep a certain NPC always loaded, in order to avoid making them pop into existence when the Player goes through a map connection.
This feature can, and was ported to Pokeemerald. However, Porymap is unable to process such objects. This can make, for example, setting their "In Connection" field a tiny bit of a pain.
*Funnily enough, I spent the better part of a day, quite some time ago, figuring out an error I was having that in the end was caused by defining incorrectly the "In Connection" field manually in the data of an cloned event object I had set up on a map.*

So essentially, I wanted to ask if it wouldn't be too much trouble to implement compatibility with these type of event objects for Pokeemerald based projects to use, if the feature is present in them.

Sierraffinity has this feature implemented in [her project, CrystalDust](https://github.com/Sierraffinity/CrystalDust), and I also have my commits where I implemented her work into my personal project public as well, see: [this commit](https://github.com/LOuroboros/pokeemerald/commit/839dc38850d0b47c88f0e6456c148d1d54f721e4) and [this one](https://github.com/LOuroboros/pokeemerald/commit/6ec00f8389b36e20b22f309e47cd038306760ef4).

**Comment by GriffinRichards** [comment]
I'm confused, currently Porymap treats these objects the same as any other object event. The only difference between them is the presence of the "In connection" toggle, which is already exposed as a config option. What issue are you having with them?

**Comment by LOuroboros** [comment]
> I'm confused, currently Porymap treats these objects the same as any other object event. The only difference between them is the presence of the "In connection" toggle, which is already exposed as a config option. What issue are you having with them?

While a custom attribute does appear in Porymap, it defaults to an empty field that can only be made "false". Trying to make it "true" doesn't actually do anything, and neither does emptying the field again.

Moreover, if you do use that custom attribute to set the "In Connection" value to false, it's written between quotation marks, which if you remember, is the problem I described above, which I also made evident in [the 2nd commit I linked](https://github.com/LOuroboros/pokeemerald/commit/6ec00f8389b36e20b22f309e47cd038306760ef4).

**Comment by LOuroboros** [comment]
Closing this. It was a bit of an error on my paty. As it was explained to me by @GriffinRichards on Pret's discord server, the In Connection field shouldn't be used as a Custom Attribute. Instead, a user needs to set the `enable_object_event_in_connection` field of the porymap.project.cfg file present in one's project's folder to 1, in order to properly modify an object's In Connection value from within Porymap.
