### ISSUE TITLE
Compiling on Arch

### ISSUE THREAD

**Issue by FieryMewtwo** [huderlem/porymap#416]
I'm new to and using Arch Linux; what packages do I need to compile porymap? (already checked the AUR...)

**Comment by garakmon** [comment]
probably `qt6-base`?

**Comment by FieryMewtwo** [comment]
i'll try it.

**Comment by ISSOtm** [comment]
The Ubuntu install instructions mention `qt5-default` and `qtdeclarative5-dev`, for which the equivalents should be `qt5-base` and `qt5-declarative`.

**Comment by FieryMewtwo** [comment]
ok
