### ISSUE TITLE
Bug: Out of Bounds Events Cannot Be Edited/Update Event Panel Suggestion

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#42]
With the current Event Viewer, out of bounds events are unreachable and therefore can't be edited.

AMap skirts around this in two ways: first, it warns you on the bottom when events are outside of the map's range when in the event view. Second, even if you can't see the event, you can head to the right panel of the event viewer, select the type of event you're looking for, and then advance through the events until you see one that is clearly out of bounds and bring it back from there by editing its coordinates. Unfortunately, porymap's event panel on the right has nothing like this. I think that this way of going through the events is needed for porymap, not only for cases where things are out of bounds but for general event editing. If you were to add this, some form of warning displayed on this panel when the event you're looking at is out of bounds would be appreciated as well.

Here is an example of AMap's Event panel. Arrow is the dropdown for the event type, circle allows you to go through each event of that type without clicking them on the map, the bracket is the event list and how AMap allows you to add or remove multiple events at a time.

![image](https://user-images.githubusercontent.com/6993375/46568482-95d31380-c913-11e8-8b5a-45c758fd36e4.png)

**Comment by huderlem** [comment]
New event editing interface from #60
