### ISSUE TITLE
Suggestion: Script Presets

### ISSUE THREAD

**Issue by oolio151** [huderlem/porymap#426]
I am pretty new to porymap and decompiled ROM editing, and something I do a lot is refer to other map scripts when I am scripting my own maps. I think adding some script presets, like basic text or leading the player somewhere would make script editing a bit faster and also help new ROM editors learn how the code works. Its a rather extensive change, but I think it could go a long way.

**Comment by GriffinRichards** [comment]
Porymap just reads the existing scripts in your project to suggest them when typing a script label. It isn't involved in creating any new scripts.
