### ISSUE TITLE
Suggestion: Allow Renaming and Reordering of Map Groups

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#43]
Renaming Map Groups is tedious and prone to error, considering labels are spread across multiple files. A way to do this in porymap and have it update these instead of doing it manually for every map would be much appreciated. In addition, reordering maps in their groups/moving maps from group to group would be a welcome feature.

**Comment by Deokishisu** [comment]
This is what needs to be done to rename a map in a group. I chose to rename everything but the individual script names and I believe that is what most people will do as well. I will use renaming Littleroot Town as an example and renaming it to Test Town:

1. Rename the LittlerootTown folder in data\maps to TestTown.
2. In the data\maps\TestTown folder, open connections.inc and rename the three labels there to TestTown_
3. In the data\maps\TestTown folder, open events.inc and rename the five labels there to TestTown_. Don't forget to rename the labels in the TestTown_MapEvents section.
4. In the data\maps\TestTown folder, open header.inc and rename the first label there to TestTown and the next four to TestTown_
5. In the data\maps\TestTown folder, open scripts.inc and rename the LittlerootTown_MapScripts:: label to TestTown_MapScripts::.
6. In the data\maps folder, open connections.inc find the line that says ".include "data/maps/LittlerootTown/connections.inc"" and rename LittlerootTown to TestTown.
7. In the data\maps folder, open groups.inc and rename LittlerootTown to TestTown.
8. In the data\maps folder, open headers.inc and find the line that says ".include "data/maps/LittlerootTown/header.inc"" and rename LittlerootTown to TestTown.
9. In the data folder, open layouts.inc and find the line that says ".include "data/layouts/LittlerootTown/layout.inc"" and rename LittlerootTown to TestTown.
10. In the data folder, open layouts_table.inc and rename LittlerootTown_Layout to TestTown_Layout.
11. In the data folder, open map_events.s and find the line that says ".include "data/maps/LittlerootTown/events.inc"" and rename LittlerootTown to TestTown.
12. Rename the LittlerootTown folder in data\layouts to TestTown.
13. In the data\layouts\TestTown folder, open layouts.inc and rename the three labels there to TestTown_. Don't forget to rename the labels within the TestTown_Layout section.
14. In the data folder, open event_scripts.s and find the line that says ".include "data/maps/LittlerootTown/scripts.inc"" and rename LittlerootTown to TestTown.
15. Now, change all references to MAP_LITTLEROOT_TOWN in your pokeemerald or pokeruby directory to MAP_TEST_TOWN. These will be in \include\constants\maps.h, the events of any map that warps to the Littleroot Town map, the connections of any map connected to Littleroot Town, and referenced in scripts if events are hidden in or a script warps the player to Littleroot Town. I had 25 hits when running a find in files search (whole word only) on my pokeemerald directory. If you don't search whole word only, your search will include other maps that have MAP_LITTLEROOT_TOWN in their names, like MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F. Be sure not to replace those.
16. In the src folder, open region_map.c, navigate down to the declaration of sMapHealLocations and change "{MAP_GROUP(LITTLEROOT_TOWN), MAP_NUM(LITTLEROOT_TOWN), HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F}," to "{MAP_GROUP(TEST_TOWN), MAP_NUM(TEST_TOWN), HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F},".
17. In the data\src\data folder, open heal_loactions.h and replace LITTLEROOT_TOWN with TEST_TOWN on lines 14 and 15. This only needs to be done if the map you're renaming is in this list.

Hopefully this will make adding functionality to do this easier, as this sucks to do manually.

**Comment by Deokishisu** [comment]
Seems that all that needs to be done to reorder map groups is to edit groups.inc in data\maps but you have to make clean after doing so because the compiler won't redo the affected labels if the files they're in weren't touched.

**Comment by huderlem** [comment]
Closing, in favor of #181
