### ISSUE TITLE
[Feature Request] Add a toggle to disable Porymap's "open the last project opened automatically" feature

### ISSUE THREAD

**Issue by LOuroboros** [huderlem/porymap#430]
> Deokishisu 03/21/2022
> I'd really like it if automatically opening the last project on startup was a toggle. It's a hassle when working with multiple projects. And, while I doubt this is a problem for many other people, when working on projects that use a fork of porymap it's extra annoying because closing the auto-opened project from another version of porymap resets the `porymap.project.cfg`.
> I'd much rather have the ability to have porymap open blank and manually load whatever project I'm working on at the moment.

> Lunos Yesterday at 11:39 PM
> In the end, this never actually happened did it? I thought it did, that's the sole reason why I built (successfully btw, it worked) Porymap from the source code 😭 

> GriffinR Today at 12:54 AM
> No that's not been added
> Could open an issue so it doesn't get lost, if one isn't already

**Comment by GriffinRichards** [comment]
I can add this, but it might not help Deokishisu's use case. 

This config option would be a Porymap config option, not a project one. If you launch a version of Porymap that doesn't have this new config option it would delete it as an unrecognized option, and when you then relaunch using a version that does have this option it would be restored with the default setting (and the default setting would be the current behavior, i.e. open the most recent project when Porymap is launched).

If all the versions of Porymap you're using to open projects have the new config option then it would help, though.
