### ISSUE TITLE
Do Not Allow Empty Text Fields

### ISSUE THREAD

**Issue by garakmon** [huderlem/porymap#437]
From #433 
Porymap probably shouldn't allow users to have empty text fields for map header data (song, location, weather, map type, battle scene), either in the new map prompt or when editing the header later.

**Comment by GriffinRichards** [comment]
I might've turned around on this? I started fixing this, but then it felt like it shouldn't be up to Porymap to enforce this. The reason it's currently "invalid" is really just down to mapjson not outputting anything reasonable for empty values.

**Comment by GriffinRichards** [comment]
This will be addressed by the changes in https://github.com/pret/pokeemerald/pull/1847
