### ISSUE TITLE
Tileset Editor returning back to old metatile after saving

### ISSUE THREAD

**Issue by HunarPG** [huderlem/porymap#443]
After you make/ edit an metatile in tileset editor and save it the tileset editor gonna refresh and instead of staying on tile you were editing it will return back to tile you were on while starting Tileset Editor

**Comment by HunarPG** [comment]
Reopening the issue as it isn't fixed yet

**Comment by GriffinRichards** [comment]
Thanks. Currently this is partially fixed: the actual selection is correctly preserved, but it still scrolls to the metatile selected in the map's metatile selector.

This is fully fixed in a branch with other upcoming changes to the Tileset Editor.

**Comment by GriffinRichards** [comment]
0b293d2af043c352a5f49b5a7e4ff40c98bc19fe
