### ISSUE TITLE
label:enhancement Ability to set preference to opening .pory instead of .inc if exists

### ISSUE THREAD

**Issue by alaxandir** [huderlem/porymap#459]
Would be a nice to have feature to allow Porymap to by default open the .pory script instead of the .inc script if a .pory script exists, could be configured by a user preferences.

**Comment by GriffinRichards** [comment]
This is a feature already. Make sure you've set `Options -> Use Poryscript`

**Comment by alaxandir** [comment]
Awesome thank you!
I just missed it.
