### ISSUE TITLE
"File -> Close Project" menu item

### ISSUE THREAD

**Issue by Rangi42** [huderlem/porymap#487]
I'd like to be able to close a project, so Porymap may open faster the next time without having to load a particular project, or just to clear my workspace before opening a different project.

**Comment by GriffinRichards** [comment]
Note that in addition to `File -> Close Project` (which will be added in the next release) version 5.0.0 added an option to disable reopening your project on startup, so if you'd prefer faster startup every time you can use that setting instead of closing your project before quitting Porymap.
