### ISSUE TITLE
Cannot follow shortcuts in Windows

### ISSUE THREAD

**Issue by Rangi42** [huderlem/porymap#488]
I have a directory full of shortcuts to project directories in Windows, for quick access. Normally I can double-click one of these and enter it like any other directory; I can pick a file from it (in file pickers) or select the clicked-through directory itself (in directory pickers). But as of porymap 5.0, the File -> Open Project directory picker complains "The folder name is not valid" when I double-click on a shortcut.

![image](https://user-images.githubusercontent.com/35663410/198888558-27d1abe6-7a8e-49df-8656-bfc87eb26795.png)

**Comment by GriffinRichards** [comment]
I can confirm this was an issue with macOS shortcuts as well (and is now fixed). Please comment if you are still able to reproduce it on Windows after the commit below

160a9c07135737a733b05f61d4afb8fc72a9cddb
