### ISSUE TITLE
Bug: Tileset Editor Changes Undone By Importing a Tileset Image Without Saving

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#49]
Steps to reproduce this in the tileset editor:
1. Edit as many metatiles as you want as long as you make at least one edit to a metatile.
2. Without saving, import a new tileset image (if you don't have a random one lying around, you can reimport the same tileset)
3. Any edits you made to the metatiles have now been undone, but they remain in your undo history, so you can hold down undo, then hold down redo to restore your work.

**Comment by huderlem** [comment]
761c25ee4c7d89105be0e7e28c369af98aa8d741
