### ISSUE TITLE
porymap.exe not opening

### ISSUE THREAD

**Issue by Mikecraft1224** [huderlem/porymap#494]
Porymap doesn't open anymore on Windows after closing it once.
Even after deleting everything and downloading it again, nothing opens, but Poryman shows up in the task manager.

**Comment by GriffinRichards** [comment]
Does it launch if you delete the Porymap config folder? On Windows that should be the folder located at `%Appdata%\pret\porymap`

**Comment by Mikecraft1224** [comment]
Yes then it opens again but stops working again while opening a project and won't start again.
So it's some kind of loop

**Comment by GriffinRichards** [comment]
What project are you attempting to open with Porymap?
