### ISSUE TITLE
Make functionality of "Export Map Stitch Image" clearer

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#499]
Without knowing what a "map stitch image" is, the functionality is not clear to a new user. The preview window only displays one map, making it unclear that more than one map is meant to be exported.

**Comment by htmlcoderexe** [comment]
For what it's worth, Google lead me here and your comment explained the functionality - I think it could be made clearer that the selected map is the one where it starts from and then explores connections.
