### ISSUE TITLE
Suggestion: option to set the number of Metatile in the porymap.project.cfg

### ISSUE THREAD

**Issue by Dragonflysots** [huderlem/porymap#500]
Currently, changing the number of metablocks can only be done in the source code of Porymap. But in projects where you either want to split metablocks differently (primary and secondary) or are ready to extend them, it would be better if you could set them in the config of Poymap. Especially when several people are working on the project, this would be much easier to control. 

It means this

https://github.com/huderlem/porymap/blob/master/include/core/block.h#L17

**Comment by GriffinRichards** [comment]
Following discussion on Discord, what's wanted is for Porymap to respect `NUM_METATILES_TOTAL` if it's increased beyond 1024 (nothing is needed in the config). Currently it's limited by that 10 bit field linked above
