### ISSUE TITLE
Warps are broken

### ISSUE THREAD

**Issue by Doesnty** [huderlem/porymap#507]
When porymap saves a map to json, it saves the field "dest_warp_id" in warp_events with redundant quotations surrounding the integer value

This confuses the mapjson script, which for some reason interprets it as 0 when writing events.inc

Which means that every warp out of a map touched by porymap will lead to destination 0

It's easily worked around by touching up the json afterwards to just remove the offending quotations but it's extremely annoying and confusing

**Comment by GriffinRichards** [comment]
This is an issue with your project being too old for the version of Porymap you're using. See the "Breaking Changes" section of Porymap 5.0.0. for the relevant necessary changes you need to make.
