### ISSUE TITLE
Sometimes porymap will break layous.json

### ISSUE THREAD

**Issue by Jaizu** [huderlem/porymap#508]
Seems to be hapenning only with this fied in this specific layout. Can't find a regular way to reproduce it.
![image](https://user-images.githubusercontent.com/18596778/213995209-a571e8e9-9b4f-473e-93df-b833ecc01ab2.png)

**Comment by GriffinRichards** [comment]
Thanks. Closing as a duplicate of <https://github.com/huderlem/porymap/issues/493>
