### ISSUE TITLE
Removing Fishing mons one by one crashes porymap

### ISSUE THREAD

**Issue by HunarPG** [huderlem/porymap#517]
When you hit configure json and remove all the fishing encounters one by one
After clicking Ok to save it crashes on the lates 5.1.0 release on windows as well on Linux
It doesn't crash if you remove non-fishing encounters by this method

**Comment by Pikabyte** [comment]
Okay, so I think this is actually some kind of issue related to the json parsing or something? Because I tried removing the fishing mons by directly editing the json, and it causes Porymap to not even want to start up.

**Comment by GriffinRichards** [comment]
940e7355d0391c1906a0d310260b2a9fccafdc48
