### ISSUE TITLE
Textboxes for colors in palette editor are buggy

### ISSUE THREAD

**Issue by cbt6** [huderlem/porymap#519]
Notice how the water turned black instead of green in the video

https://user-images.githubusercontent.com/91667135/218334530-4ee8f150-81de-42fe-a711-d02377afd1fb.mp4

**Comment by GriffinRichards** [comment]
To add on to this, the color isn't set correctly when using the text boxes in 15-bit mode

![ctest](https://user-images.githubusercontent.com/25753467/219904693-3edd624a-70eb-4f33-8a78-26173c753cdf.gif)

**Comment by GriffinRichards** [comment]
420e92e91259276fc7582c7672fe5e4cd935b93f
