### ISSUE TITLE
Suggestion: Change Save Prompt When Exiting Tileset Editor

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#52]
The way porymap handles asking to save when exiting the tileset editor is backwards, in my opinion. The vast majority of the time someone opens the tileset editor, makes an edit, and then tries to exit, they will want that change saved.

So, instead of asking whether or not to discard and then forcing us to manually save when we say no, ask us whether we want to save when we exit the tileset editor with unsaved changes. If yes, save and exit. If no, just exit. If cancel, return to the tileset editor. You will save people a ton of time with this simple change.

**Comment by huderlem** [comment]
62c1ed2dc7c777b169c591701a15b3c9a35cda2b
