### ISSUE TITLE
Incorrect draw preview on prefab after using eyedropper

### ISSUE THREAD

**Issue by shyperson0** [huderlem/porymap#542]
To reproduce: Open porymap, select a prefab, then eyedropper and use the pencil to draw a tile. From now on, selecting a prefab will show a 1x1 square instead of the prefab size, same for picking several tiles from the map. Choosing several tiles from the tileset panel will fix this.
I'm using porymap through wine, will confirm if it happens in windows in a couple hours.
[output.webm](https://github.com/huderlem/porymap/assets/91394210/950c41c9-3c37-4c40-9fef-5f1317f02a82)

**Comment by GriffinRichards** [comment]
Thanks! Fixed
ae68ab3a6fee00b1030bb792077941499045bb08
