### ISSUE TITLE
Implement some kind of Zoom or scaling for Metatiles.

### ISSUE THREAD

**Issue by Gamer2020** [huderlem/porymap#55]
Decided to use this on my surface tablet which has a high resolution. Noticed that the tiles were really small and didn't find a way to zoom in on them.

![image](https://user-images.githubusercontent.com/6243575/46919058-6e311a80-cfa7-11e8-9271-57cc75d6b290.png)

**Comment by phase** [comment]
Ctrl + Scrolling the mouse wheel will zoom in the map tiles.

**Comment by garakmon** [comment]
I think they mean the metatiles on the right

**Comment by Gamer2020** [comment]
Yes on the right. I can zoom in on the map no problem but the metatiles are extremely small.

**Comment by Deokishisu** [comment]
I'd like to add to this issue. Not only should the metatiles in the right panel be zoomable in the map view, but also the panels the tileset editor. Gamer2020 will run into the same problem there.

**Comment by Gamer2020** [comment]
Confirmed. Not as small but still the same thing.

![image](https://user-images.githubusercontent.com/6243575/46920625-1c948a00-cfbf-11e8-8709-f3b955541988.png)

**Comment by Gamer2020** [comment]
Zoomed in picture for reference of size difference.

![image](https://user-images.githubusercontent.com/6243575/46920628-3d5cdf80-cfbf-11e8-8430-b7377760d9e8.png)

**Comment by Gamer2020** [comment]
Sweet, I'll try to test tonight.

**Comment by Gamer2020** [comment]
Just tested. Works great, thank you!

**Comment by Gamer2020** [comment]
Actually, just noticed this. Tolerable but just thought I should point it out.

![image](https://user-images.githubusercontent.com/6243575/52923840-b9fa2480-32f7-11e9-8563-523a5c142aa5.png)
