### ISSUE TITLE
Bug: event objects can leave the established grid if you swap back and forth between 32x32 and 16x32 sprites

### ISSUE THREAD

**Issue by LOuroboros** [huderlem/porymap#551]
Title.

I found this kinda randomly just now, but if you place the cursor on top of an event object such as a berry tree and switch its sprite a few times going to one of the big 32x32 doll sprites and back to "the berry tree sprite", suddenly, the object in question will leave the established grid.

I'm really not sure at all how to properly describe this, so here's a small video showing it in action:

https://github.com/huderlem/porymap/assets/4485172/0edcb7c5-422d-4ecd-90c5-e97548480e85

**Comment by GriffinRichards** [comment]
Thanks, this was already fixed (0b6d61e)

**Comment by LOuroboros** [comment]
> Thanks, this was already fixed ([0b6d61e](https://github.com/huderlem/porymap/commit/0b6d61e3f183746f3cdd8432a1a55a599a95b0c7))

Oh. Makes sense. Since the last precompiled build of Porymap for Windows is from February, it doesn't have that fix :P ...
