### ISSUE TITLE
Special characters in MAPSEC names break the region_map_entries.h file and unables to build the project

### ISSUE THREAD

**Issue by ExcmoJack** [huderlem/porymap#557]
I noticed that when a MAPSEC name has an special character in Region Map Editor it is written in region_map_sections.json, and then converted into code in region_map_entries.h.

The issue is that when typing `Pokémon` in the JSON it becomes `Pok__mon` in the .h, converting that `é` character into `__`for some reason. However, when typing another special character like `á` it becomes a `�`, impeding to build the project due to syntax errors:

Region Map Editor:
![imagen](https://github.com/huderlem/porymap/assets/13456877/48a3a951-5fe5-4e8e-8029-c8c7b77b3c6d)

region_map_sections.json:
![imagen](https://github.com/huderlem/porymap/assets/13456877/ac70ce43-430f-4082-b4a2-df23d370764d)

region_map_entries.h:
![imagen](https://github.com/huderlem/porymap/assets/13456877/2e72c1ea-7619-4f69-8841-0d4500189c57)

I know not anybody makes a game in Spanish (or whatever language which uses special characters as tildes or etc), but there is a solution already implemented for this issue, but just for the `é` character in _Pokémon_. What I propose is to extend this behavior to all special characters, replacing them with `__` as for now or replacing them for the same character without the _tilde_.

**Comment by GriffinRichards** [comment]
It looks like Porymap correctly output your name in the JSON file. This would be an issue with `jsonproc` in pokeemerald (or whichever repo you're using), i.e the tool responsible for converting that JSON data to C

**Comment by ExcmoJack** [comment]
Oh, I got it, I thought it was part of porymap. Thanks!

**Comment by GriffinRichards** [comment]
Thanks for the report regardless! I opened an issue in pokeemerald to track this problem
