### ISSUE TITLE
Linux prebuild

### ISSUE THREAD

**Issue by jowin202** [huderlem/porymap#611]
Hello,

Thank you for this great project. If it's possible, I saw there is a workflow for windows, macos and linux. however, there is only the windows and macos prebuild in the releases section. Is it possible to also add a prebuild porymap-linux file?

thank you very much.

**Comment by GriffinRichards** [comment]
At the moment we have no active contributors that use Linux, so it's unlikely to get done until someone takes an interest (you're more than welcome to modify the workflow yourself to do this!).

In the meantime, some other options are following [INSTALL.md](https://github.com/huderlem/porymap/blob/master/INSTALL.md#ubuntu) to compile Porymap locally (make sure to check out the commit of the latest release, 199799f1c2bda5201d5a0f6172226c30d4498252), or you can check out the build of Porymap on Flatpak that someone else maintains. A build for Porymap was also uploaded to AUR, but I don't believe it's actively maintained so I wouldn't recommend that.

**Comment by jowin202** [comment]
The thing is that I only have machine with Qt6 installed. And I’m afraid of killing my whole Build Environment by having two different versions of qt. I already tried with Qt6 but this does not work for me :/

I’ll try to modify the workflow. Alternatively, I’ll try to get some virtual machine
