### ISSUE TITLE
Bug: Don't crash on startup

### ISSUE THREAD

**Issue by jmwielandt** [huderlem/porymap#62]
Hi, I'm using yout tool to develop a proyect on pokeruby, but sth I really need is to know why pory don't want to open (if i've deleted something or whatever).

If you improve this on a future version it will be awesome.

Thx.

**Comment by huderlem** [comment]
I thought this issue for startup crash was already created--renaming.

**Comment by huderlem** [comment]
40257193a4b50186f97290cbd13f855dda89e6cd
