### ISSUE TITLE
[enhancement] update libraries

### ISSUE THREAD

**Issue by Emil2010** [huderlem/porymap#628]
not too important, when libraries is outdated, it's recommended to update to new version

**Comment by GriffinRichards** [comment]
Hi, thanks for the issue. What libraries are you talking about?

**Comment by Emil2010** [comment]
since, porymap uses c++ (.net is not mentioned) and QT 5.14.2 (QT 6.8 LTS is latest LTS), python (very small usage, version unknown), very little C, and somehow written in batchfile and makefile. You can update them, if you want unless libraries outdated

**Comment by GriffinRichards** [comment]
These are all things that would be installed in your environment and are up to you to update, not something Porymap provides (or can update for you) with the exception of our static Windows release build (which we will update at some point)
