### ISSUE TITLE
[Suggestion/FR] Allow displaying a separator between tilesets

### ISSUE THREAD

**Issue by Jaizu** [huderlem/porymap#648]
This is very annoying when you are making new tilesets, it would be nice to have an option to separate them. I don't think anything wild is needed, just a line to separate them or something like that would do.

![image](https://github.com/user-attachments/assets/c1a07fd2-d0fa-4795-93ba-9f0feabb3afd)

**Comment by GriffinRichards** [comment]
64a9e2cacbc93440e82ebb6b159c7abc5433b72e
