### ISSUE TITLE
Metatile selection area gets off-center when switching to another map through the connections tab

### ISSUE THREAD

**Issue by i0brendan0** [huderlem/porymap#657]
When editing a map's metatiles, switch to the connections tab, daouble-click on another map to open it, then go back to the map editor. The metatiles will be off-center, possibly causing some of them not to be visible until the scale bar is moved. The border and selection area gets pushed to the top left as well.

Normal
![image](https://github.com/user-attachments/assets/5c199727-56b1-49a7-b0da-f518560d8963)

After switching maps through the connections tab
![image](https://github.com/user-attachments/assets/36598f85-b38f-4840-b32b-b7d4efdc12e5)

**Comment by GriffinRichards** [comment]
ad0b8d6794f4bb63e0e01078b21d3b41e957c5cf
