### ISSUE TITLE
porymap can crash while changing the number of metatiles in a tileset

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#68]
I encountered several crashes by continually changing the number of metatiles in the secondary tileset. I specifically remember having a crash after changing from 45 to 40. I was only reducing the number of metatiles, but the crash happens inconsistently so it was difficult to reproduce going the other way.

**Comment by huderlem** [comment]
This happens when you have a metatile selected that no longer exists after the size change.

**Comment by huderlem** [comment]
Fixed: 36b7f361cf58413c015861c81cc23480d680196c
