### ISSUE TITLE
Cannot flip through the palettes in the tileset viewer with arrow keys

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/porymap#69]
See how I'm highlighting the palette number? Pressing the up or down arrow keys on my keyboard changes the red value of color 4 instead of flipping through the palettes.

![image](https://user-images.githubusercontent.com/6993375/50566622-f3f07680-0d09-11e9-8900-ba2f7a0772ee.png)

**Comment by huderlem** [comment]
99a71afbfe360ff61a37e6d91d9ea141b3ba716e
