### ISSUE TITLE
Suggestion: Import tileset palettes

### ISSUE THREAD

**Issue by Diegoisawesome** [huderlem/porymap#71]
Have a dropdown menu in the palette editor that allows you to import palettes.

**Comment by huderlem** [comment]
From what format(s)?  JASC?  Something from A-Map?

**Comment by Diegoisawesome** [comment]
JASC and whatever A-Map uses would be my top picks.

**Comment by huderlem** [comment]
851f8ec8132e8161c0e9ea3c15d19267b0f9d1d9
