### ISSUE TITLE
Feature Request: Export Tileset images in a given palette

### ISSUE THREAD

**Issue by SBird1337** [huderlem/porymap#73]
When working with similar Map Editors one could always export a tileset image in a given palette, in order to further edit in a gfx editor. Not every gfx editor can read JASC palette files, and if they can it is probably easier to just open the exported image file and go from there.

**Add a Button to the dropdown menu that lets you export the tileset base image in the currently selected palette**

**Comment by huderlem** [comment]
Added in f1caa03c6c40baebd4f5599fb979e9b7c359c0e8
