### ISSUE TITLE
[Bug] Wierd behaviour when multiple tiles selected - smart paths issue

### ISSUE THREAD

**Issue by jmwielandt** [huderlem/porymap#88]
Hi, 
I was working on my project when a wierd bug appears. 

![image](https://user-images.githubusercontent.com/37153467/51191266-c89d8800-18c2-11e9-9814-af84cd8682bc.png)

Clicking on the "X":
![image](https://user-images.githubusercontent.com/37153467/51191244-bae80280-18c2-11e9-9405-d1a2975cef6b.png)

Trying in more places:
![image](https://user-images.githubusercontent.com/37153467/51191746-d3a4e800-18c3-11e9-99df-059c1a76710e.png)

As you can see on the last pic, smart paths are disabled but pory act as if it is. Enabling and then disabling it fixes the bug.

Porymap 1.1.0 windows.

**Comment by garakmon** [comment]
this was fixed with 95f712ef6f9d9f9ac713b769832b6ddf29ceb19c
