### ISSUE TITLE
Handle Metatile Behavior correctly for pokeemerald

### ISSUE THREAD

**Issue by SBird1337** [huderlem/porymap#92]
For pokeemerald the metatile behaviors are actually a bitfield, and things are a little different in general, e.g. the metatile behavior itself is 9 bits long and there are seperate fields for hm usage and encounter type.

Ill do some digging and add a struct layout!

**Comment by Diegoisawesome** [comment]
This isn't right for pokeemerald though, Emerald only uses two bytes for the behavior byte.

**Comment by huderlem** [comment]
This will eventually be addressed whenever pokefirered happens.  The current implementation is correct for emerald and ruby.
